package utils

const (
	Name                       string = "name"
	Region                     string = "region"
	ClusterId                  string = "cluster-id"
	ControllerClusterId        string = "controller-cluster-id"
	SpotPercentage             string = "spot-percentage"
	DrainingTimeout            string = "draining-timeout"
	UtilizeReserveInstances    string = "utilize-reserved-instances"
	FallbackOnDemand           string = "fallback-ondemand"
	MinSize                    string = "min-size"
	MaxSize                    string = "max-size"
	TargetSize                 string = "target-size"
	SubnetIds                  string = "subnet-ids"
	InstancesTypesWhitelist    string = "instance-types-whitelist"
	InstancesTypesBlacklist    string = "instance-types-blacklist"
	SecurityGroupIds           string = "security-group-ids"
	ImageIds                   string = "image-id"
	KeyPair                    string = "key-pair"
	UserData                   string = "user-data"
	RootVolumeSize             string = "root-volume-size"
	AssociatePublicIpAddress   string = "associate-public-ip-address"
	EnableMonitoring           string = "enable-monitoring"
	EnableEbsOptimization      string = "enable-ebs-optimization"
	IamInstanceProfileName     string = "iam-instance-profile-name"
	IamInstanceProfileArn      string = "iam-instance-profile-arn"
	LoadBalancerName           string = "load-balancer-name"
	LoadBalancerArn            string = "load-balancer-arn"
	LoadBalancerType           string = "load-balancer-type"
	EnableAutoScaler           string = "enable-auto-scaler"
	EnableAutoScalerAutoconfig string = "enable-auto-scaler-autoconfig"
	Cooldown                   string = "cooldown"
	HeadroomCpuPerUnit         string = "headroom-cpu-per-unit"
	HeadroomMemoryPerUnit      string = "headroom-memory-per-unit"
	HeadroomGpuPerUnit         string = "headroom-gpu-per-unit"
	HeadroomNumPerUnit         string = "headroom-num-per-unit"
	ResourceLimitMaxVcpu       string = "resource-limit-max-vcpu"
	ResourceLimitMaxMemory     string = "resource-limit-max-memory"
	EvaluationPeriods          string = "evaluation-periods"
	MaxScaleDownPercentage     string = "max-scale-down-percentage"
)
